language: java

jdk:
- openjdk8
- openjdk11

addons:
  apt:
    packages:
    - libxml2-utils

before_install:
- export REPO_SLUG=$TRAVIS_REPO_SLUG
- export BRANCH=$TRAVIS_BRANCH
- export PULL_REQUEST=$TRAVIS_PULL_REQUEST
- export RUN_ITS=$TRAVIS_SECURE_ENV_VARS
- if [ "${TRAVIS_EVENT_TYPE}" = "cron" ] ; then export CRON=true; fi
- source ./src/ci/before_install.sh

# skip the Travis-CI install phase because Maven handles that directly
install:
- 'true'

script:
- "./src/ci/build.sh"

after_success:
- bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml
